Update 5.1
AnacondaRecipes/django-feedstock pull request #13
Opened 2024-08-16 02:10 UTC by Arishamays1

2024-08-16 02:12 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_76m3_fgf1i/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:219: missing_description: The recipe is missing a description
- clone/recipe/meta.yaml:219: license_file_overspecified: Using license_file and license_url is overspecified.

===== ERRORS =====
- clone/recipe/meta.yaml:219: http_url: http://www.djangoproject.com/ is not https
- clone/recipe/meta.yaml:14: pip_install_args: `pip install` should be run with --no-deps and --no-build-isolation.
===== Final Report: =====
2 Errors and 2 Warnings were found

</details>

2024-08-19 13:45 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_e5jgws7avb/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:209: license_file_overspecified: Using license_file and license_url is overspecified.
- clone/recipe/meta.yaml:209: missing_description: The recipe is missing a description

===== ERRORS =====
- clone/recipe/meta.yaml:209: http_url: http://www.djangoproject.com/ is not https
===== Final Report: =====
1 Error and 2 Warnings were found

</details>

2024-08-21 02:14 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_f2x5rr2tx2/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:26: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-08-21 18:29 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_0cyuq7h0un/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:24: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
===== Final Report: =====
0 Errors and 1 Warning were found

</details>

2024-08-27 15:50 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_bfiukgxnc6/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:27: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.
- clone/recipe/meta.yaml:27: build_tools_must_be_in_build: The build tool patch is not in the build section.

===== ERRORS =====
- clone/recipe/meta.yaml:1: patch_must_be_in_build: patch must be in build when source/patches is set.
- clone/recipe/meta.yaml:19: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
2 Errors and 2 Warnings were found

</details>

2024-08-27 16:00 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_4eetqs5kir/clone` failed. (See above for error)
The following problems have been found:

===== WARNINGS =====
- clone/recipe/meta.yaml:30: build_tools_must_be_in_build: The build tool patch is not in the build section.
- clone/recipe/meta.yaml:30: host_section_needs_exact_pinnings: Linked libraries host should have exact version pinnings.

===== ERRORS =====
- clone/recipe/meta.yaml:19: patch_unnecessary: patch should not be in build when source/patches is not set
- clone/recipe/meta.yaml:24: patch_must_be_in_build: patch must be in build when source/patches is set.
===== Final Report: =====
2 Errors and 2 Warnings were found

</details>

2024-08-27 16:10 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_31uql1vbmt/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:17: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-27 16:17 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_74v17mmvrp/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:17: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-27 17:41 UTC, cbouss commented on recipe/meta.yaml
> +    - 001-Win-tzdata-removal   # [win]
```suggestion
    - patches/001-Win-tzdata-removal.patch   # [win]
```

2024-08-27 17:41 UTC, cbouss commented on recipe/patches/001-Win-tzdata-removal
Can you rename to 001-Win-tzdata-removal.patch?
And add a comment at the top of the file explaining why this is needed. (python-tzdata is a fallback package for systems not providing timezone data, but the conda python package depends on tzdata. Therefore we do not need to depend on python-tzdata.)

2024-08-27 18:32 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_bfgmilw0r8/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:17: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-27 18:33 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_b5ruyv4oe_/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:17: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-27 18:33 UTC, Arishamays1 commented on recipe/patches/001-Win-tzdata-removal
will do! thanks!

2024-08-27 18:35 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_5d1oq1vqmq/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:19: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-28 07:49 UTC, skupr-anaconda requested changes

2024-08-28 07:49 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - sqlparse >=0.3.1
```suggestion
    - sqlparse >=0.3.1
  run_constrained:
    - argon2-cffi >=19.1.0
```
See https://github.com/django/django/blob/5.1/pyproject.toml#L41C11-L41C30

2024-08-28 07:49 UTC, skupr-anaconda commented on recipe/meta.yaml
> +
```suggestion
```

2024-08-28 07:49 UTC, skupr-anaconda commented on recipe/meta.yaml
> +    - setuptools
```suggestion
    - setuptools >=61.0.0,<69.3.0
```
There are upstream issues with case sensitivity in **setuptools >=69.3.0**, see:

- https://github.com/django/django/blob/5.1/pyproject.toml#L2
- https://github.com/django/django/commit/b4dd76c315ff06e4897fd380e0ad0eaf88db8a9d
- https://github.com/django/django/pull/17806#discussion_r1609743375

2024-08-28 16:18 UTC, anaconda-pkg-build commented
<details><summary>Linter check found the following problems:</summary>
ERROR conda.cli.main_run:execute(125): `conda run conda-lint /tmp/abs_81acobk_zj/clone` failed. (See above for error)
The following problems have been found:

===== ERRORS =====
- clone/recipe/meta.yaml:19: patch_unnecessary: patch should not be in build when source/patches is not set
===== Final Report: =====
1 Error and 0 Warnings were found

</details>

2024-08-29 07:26 UTC, skupr-anaconda approved these changes

2024-08-29 18:10 UTC, cbouss approved these changes

2024-08-29 18:10 UTC, cbouss commented on recipe/meta.yaml
> +    - patch   # [unix]
```suggestion
```
The patch is only applied on windows

2024-08-29 18:10 UTC, cbouss commented on recipe/meta.yaml
> +    - setuptools
I wouldn't take this, it doesn't apply to our packaging and makes maintenance more difficult.

2024-08-29 20:45 UTC, merged